### ISSUE TITLE
weatherPhrase is not an int

### ISSUE THREAD

**Issue by sn3ak** [jamesnw/statstat#5]
php cron.php
INSERT INTO `stat`(coolLowerSetpLimit, coolNextPeriod, coolSetpoint, coolUpperSetptLimit, deviceID, dispTemperature, displayedUnits, heatLowerSetptLimit, heatNextPeriod, heatSetpoint, heatUpperSetptLimit, isInVacationHoldMode, schedCoolSp, schedHeatSp, scheduleCapable, statusCool, statusHeat, systemSwitchPosition, weatherHumidity, weatherPhrase, weatherTemperature) VALUES (50.0000, 0, 76.0000, 99.0000, secured, 81.0000, 'F', 40.0000, 0, 62.0000, 90.0000, false, 76.0000, 62.0000, true, 0, 0, 2, '64', 'Mostly clear', '72')
Errormessage: Incorrect integer value: 'Mostly clear' for column 'weatherPhrase' at row 1

note: I purposely changed the unit #

**Comment by jamesnw** [comment]
Future installs will have this fixed. To fix existing installs, update the following columns which got switched-

`weatherHumidity` int(11) NOT NULL
`weatherPhrase` varchar(32) COLLATE latin1_german2_ci NOT NULL

**Comment by sn3ak** [comment]
Thank you
