### ISSUE TITLE
Support multiple thermostats

### ISSUE THREAD

**Issue by sn3ak** [jamesnw/statstat#6]
TSIA

**Comment by jamesnw** [comment]
This is currently supported in theory, but I'll leave this issue open until we have proof of success.

The structure is found here- https://github.com/jamesnw/statstat/wiki/Plugin-structure. I've added this to the README so it's easier to find.

Individual thermostat requests should be added as separate issues.

**Comment by sn3ak** [comment]
Hmm. I don't think we are on the same page, but maybe we are. My buddy has 2 Honeywell thermostats in his house. Ideally he would like to log both at the same time. I'd imagine we would need an array of devices/settings to be able to handle multiple devices; additionally the gui would need a drop down or some such to be able to select the different thermostats.

**Comment by jamesnw** [comment]
Oh, I see. I did misunderstand. Changed the title back. This is a rather large task. The current database setup would be able to handle this (it logs the device id), but it would take a lot of code changes to log multiple thermostats on one install. 

This will probably not be my top priority on this project- if you're willing to take it on, that would make it happen a lot quicker.

**Comment by sn3ak** [comment]
I might be able to. It's not for me personally, so not a priority. I have a few ideas on how to tackle it. If I come up with something I'll let you know

**Comment by dorfl68** [comment]
I just did this. However, the code changes a bit. what's the best way to contribute, as every module changes?

**Comment by jamesnw** [comment]
Thanks for the updates!
